package com.ecommerce.checkout.application.validation;

public enum CloseBasketValidationResult {
	SUCCESS, TOTAL_PRICE_SHOULD_BE_LESS_THAN_OR_EQUAL_1500, TOTAL_PRICE_SHOULD_BE_GREATER_THAN_100, THERE_ARE_SOME_ITEMS_THAT_ARE_NOT_AVAILABLE
}
